export { PACKAGE_VERSION } from "./shared/const";
export {
  CARD_NAME,
  CARD_TITLE,
  CARD_VERSION,
  DEFAULT_OFF_LABEL,
  DEFAULT_POWER_LABEL,
  DEFAULT_TITLE,
  EDITOR_SELECT_EVENT,
  MAX_RESOLVED_STAGES,
  MAX_STAGES,
} from "./cards/staged-switch/const";
export {
  CONTROL_DOMAINS,
  DOCUMENTATION_URL,
  ENTITY_ID_PATTERN,
  MAX_ENTITY_BUTTONS_PER_ROW,
} from "./shared/const";
